my_string = input('Введите Ваше местр жительства: ' )
print(my_string)
print(len (my_string))
name = 'Я привык бродить один'
print(name)
print(name.upper())
print(name.lower())
print(name.replace(' ',''))
print(name.replace(' ','#'))
print(name[0])
print(name[-1])
